Vagrant.configure("2") do |config|

  config.vm.define "apache-custom" do |a|
    a.vm.synced_folder "html", "/var/www", type: "rsync"
    a.vm.provider "docker" do |d|
      d.build_dir = "./apache_container/"
      d.build_args = ["-t=apache2"]
      d.ports = ["8080:80"]
      d.name = "apache-custom"
      d.remains_running = true
      d.vagrant_machine = "vagrant-proxy"
      d.vagrant_vagrantfile = "./proxy-vm/Vagrantfile"
    end
  end

  # config.vm.define "postgres-custom" do |p|
  #   p.vm.provider "docker" do |d|
  #     d.image = "postgres"
  #     d.name = "postgres-custom"
  #     d.remains_running = true
  #     d.vagrant_vagrantfile = "./proxy-vm/Vagrantfile"
  #   end
  # end

  config.vm.define "con-test-custom" do |c|
    c.vm.provider "docker" do |d|
      d.build_dir = "./con_test_container/"
      d.build_args = ["-t=con-test"]
      d.name = "con-test-custom"
      d.link("apache-custom:apache")
      d.remains_running = true
      d.vagrant_machine = "vagrant-proxy"
      d.vagrant_vagrantfile = "./proxy-vm/Vagrantfile"
    end
  end

end
