# Source ==> https://github.com/mitchellh/vagrant/blob/master/plugins/providers/docker/hostmachine/Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "mitchellh/boot2docker"

  config.vm.provision "docker"
  config.vm.provision "shell", inline:
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"


  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
    v.name = "vagrant-proxy"
  end

  ["vmware_fusion", "vmware_workstation"].each do |vmware|
    config.vm.provider vmware do |v|
      if v.respond_to?(:functional_hgfs=)
        v.functional_hgfs = false
      end
      v.name = "vagrant-proxy"
    end
  end

  # b2d doesn't support NFS
  config.nfs.functional = false

  config.vm.network "forwarded_port",
    guest: 8080, host: 8080

  config.vm.define "vagrant-proxy" do |pv|
  end

  config.vm.provider :virtualbox do |vb|
      vb.name = "vagrant-proxy"
  end

end
