ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|

  config.vm.define "apache" do |a|
#    a.vm.network :forwarded_port, guest: 8080,host: 8080
    a.vm.synced_folder "html", "/var/www"
    a.vm.provider "docker" do |d|
      d.build_dir = "./apache_container/"
      d.build_args = ["-t=apache2"]
      d.ports = ["8080:80"]
      d.name = "apache"
      d.remains_running = true
    end
  end

  config.vm.define "postgres" do |p|
    p.vm.provider "docker" do |d|
      d.image = "postgres"
      d.name = "postgres"
      d.remains_running = true
    end
  end

  config.vm.define "con-test" do |c|
    c.vm.provider "docker" do |d|
      d.build_dir = "./con_test_container/"
      d.build_args = ["-t=con-test"]
      d.name = "con-test"
      d.link("apache:apache")
      d.remains_running = true
    end
  end

end
