Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision "docker"
  config.vm.provision "shell", inline:
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.define "vagrant-proxy" do |pv|
  end
  config.vm.provider :virtualbox do |vb|
      vb.name = "vagrant-proxy"
  end
end
